=== Alexey-99/Epam_Training/xml_parsing/src/main/resources/xml_files/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.flowers.com/Flowers" xmlns:tns="http://www.flowers.com/Flowers">
	<xsd:element name="Flowers">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Flower" type="tns:Flower" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="Flower">
		<xsd:sequence>
			<xsd:element name="Name" type="tns:Name" />
			<xsd:element name="Soils" type="tns:Soils" />
			<xsd:element name="Origin" type="tns:Origin" />
			<xsd:element name="VisualParameters" type="tns:VisualParameters" />
			<xsd:element name="GrowingTips" type="tns:GrowingTips" />
			<xsd:element name="Multiplying" type="tns:Multiplying" />
			<xsd:element name="PlantingDate" type="xsd:dateTime"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:ID" use="required" />
	</xsd:complexType>
	<xsd:simpleType name="ID">
		<xsd:restriction base="xsd:ID">
			<xsd:pattern value="\w+" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Name">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(\w+(\s?\w))+"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Soils">
		<xsd:sequence>
			<xsd:element name="Soil" type="tns:Soil" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="Soil">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\w+(\s\w+)*"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Origin">
		<xsd:sequence>
			<xsd:element name="Region" type="tns:Region" />
			<xsd:element name="Century" type="tns:Century"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="Region">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="([A-Z][a-z]+(\s[A-Za-z]+)*)|[A-Z]+"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Century">
		<xsd:restriction base="xsd:positiveInteger">
			<xsd:pattern value="\d{2}"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="VisualParameters">
		<xsd:sequence>
			<xsd:element name="StemColor" type="xsd:string" default="green" />
			<xsd:element name="LeafColor" type="xsd:string" default="green" />
			<xsd:element name="AveragePlantSize" type="tns:AveragePlantSize"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AveragePlantSize">
		<xsd:simpleContent>
			<xsd:extension base="xsd:positiveInteger">
				<xsd:attribute name="measure" type="tns:Measure" default="sm"></xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:simpleType name="Measure">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-z]+"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="GrowingTips">
		<xsd:sequence>
			<xsd:element name="Temperature" type="tns:Temperature" />
			<xsd:element name="Lighting" type="xsd:boolean" default="true" />
			<xsd:element name="Watering" type="tns:Watering" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Temperature">
		<xsd:simpleContent>
			<xsd:extension base="tns:Temperature-content">
				<xsd:attribute name="measure" type="tns:Temperature-measure" default="Â°C"></xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:simpleType name="Temperature-content">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(\+|\-)\d+"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Temperature-measure">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\w+"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Watering">
		<xsd:simpleContent>
			<xsd:extension base="xsd:positiveInteger">
				<xsd:attribute name="measure" type="tns:Watering-measure"></xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:simpleType name="Watering-measure">
		<xsd:restriction base=" xsd:string">
			<xsd:pattern value="[a-z]+\/[a-z]+"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Multiplying">
		<xsd:sequence>
			<xsd:element name="Method" maxOccurs="7">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="SEEDS"></xsd:enumeration>
						<xsd:enumeration value="LAYERING"></xsd:enumeration>
						<xsd:enumeration value="GRAFTING FROM BUDS (BUDDING)"></xsd:enumeration>
						<xsd:enumeration value="CUTTINGS"></xsd:enumeration>
						<xsd:enumeration value="DIVISION OF RHIZOMES"></xsd:enumeration>
						<xsd:enumeration value="DIVISION THE BUSH"></xsd:enumeration>
						<xsd:enumeration value="DIVISION TUBERS"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== Alexey-99/Epam_Training/xml_parsing/src/main/resources/xml_files/flowersSAX.xml
<?xml version="1.0" encoding="UTF-8"?><Flowers xmlns="http://www.flowers.com/Flowers" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.flowers.com/Flowers flowers.xsd"><Flower id="f1"><Name>Rose</Name><Soils><Soil>light</Soil><Soil>loamy</Soil><Soil>medium loamy</Soil></Soils><Origin><Region>Persia</Region><Century>19</Century></Origin><VisualParameters><StemColor>green</StemColor><LeafColor>green</LeafColor><AveragePlantSize measure="sm">70</AveragePlantSize></VisualParameters><GrowingTips><Temperature measure="°C">-5</Temperature><Lighting>true</Lighting><Watering measure="ml/week">10</Watering></GrowingTips><Multiplying><Method>SEEDS</Method><Method>LAYERING</Method><Method>GRAFTING FROM BUDS (BUDDING)</Method><Method>CUTTINGS</Method></Multiplying><PlantingDate>2015-03-06T10:23:05</PlantingDate></Flower><Flower id="f2"><Name>Alstroemeria</Name><Soils><Soil>clay</Soil><Soil>sandy</Soil></Soils><Origin><Region>Peru</Region><Century>17</Century></Origin><VisualParameters><StemColor>green</StemColor><LeafColor>green</LeafColor><AveragePlantSize measure="sm">150</AveragePlantSize></VisualParameters><GrowingTips><Temperature measure="°C">+19</Temperature><Lighting>true</Lighting><Watering measure="ml/week">5</Watering></GrowingTips><Multiplying><Method>SEEDS</Method><Method>GRAFTING FROM BUDS (BUDDING)</Method></Multiplying><PlantingDate>2018-08-20T12:08:10</PlantingDate></Flower><Flower id="f3"><Name>Aquilegia Colombian</Name><Soils><Soil>loose moist</Soil></Soils><Origin><Region>Colombia</Region><Century>15</Century></Origin><VisualParameters><StemColor>green</StemColor><LeafColor>green</LeafColor><AveragePlantSize measure="sm">100</AveragePlantSize></VisualParameters><GrowingTips><Temperature measure="°C">+18</Temperature><Lighting>true</Lighting><Watering measure="ml/week">6</Watering></GrowingTips><Multiplying><Method>SEEDS</Method><Method>DIVISION THE BUSH</Method></Multiplying><PlantingDate>2008-02-01T08:11:05</PlantingDate></Flower><Flower id="f4"><Name>Amorphophallus titanic</Name><Soils><Soil>garden soil and sand</Soil></Soils><Origin><Region>Sumatra island</Region><Century>18</Century></Origin><VisualParameters><StemColor>green</StemColor><LeafColor>green</LeafColor><AveragePlantSize measure="sm">300</AveragePlantSize></VisualParameters><GrowingTips><Temperature measure="°C">+25</Temperature><Lighting>true</Lighting><Watering measure="ml/week">20</Watering></GrowingTips><Multiplying><Method>DIVISION TUBERS</Method></Multiplying><PlantingDate>2021-11-04T09:11:05</PlantingDate></Flower><Flower id="f5"><Name>African daisies</Name><Soils><Soil>fertile loose</Soil></Soils><Origin><Region>South Africa</Region><Century>13</Century></Origin><VisualParameters><StemColor>green</StemColor><LeafColor>green</LeafColor><AveragePlantSize measure="sm">23</AveragePlantSize></VisualParameters><GrowingTips><Temperature measure="°C">+15</Temperature><Lighting>true</Lighting><Watering measure="ml/week">15</Watering></GrowingTips><Multiplying><Method>SEEDS</Method></Multiplying><PlantingDate>2003-04-05T08:09:10</PlantingDate></Flower></Flowers>
